properties:
    ### User properties (you can modify this)
    prometheus_url: http://localhost:9090
    job: "quarkus-app"
    refresh_seconds: 10
    period: 10m
    window: 10s

    # style
    subTitleStyle: "padding: 5px; background-color: #F1F1F1; font-size: medium; font-weight: bolder; margin: 5px"
    titleStyle: "font-size: x-large; margin: 10px; font-weight: bold"

    ### Internal Properties
    time_window: "[${period}:${window}]"
    global_filter: 'job="${job}"'
global:
    mode: dark
    dataset:
        url: ${prometheus_url}
        type: prometheus
        path: /api/v1/query
        cacheEnabled: true
        refreshTime: "1second"
    displayer:
        refresh:
            interval: ${refresh_seconds}
        extraConfiguration: >-
            {
                "xAxis": {
                    "splitNumber": 3
                },
                "title": {
                    "textStyle" : { 
                        "fontSize" : 15
                    }
                }
            }
        axis:
            y:
                labels_show: false
        chart:
            resizable: true
            height: 180
            zoom: true
            grid:
                x: false
            margin:
                bottom: 20
                top: 35
            legend:
                show: false

        html:
            html: >-
                    <div style="width: 95%;height: auto;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;">
                    <div class="pf-v5-c-card pf-m-compact pf-m-rounded">    
                            <div class="pf-v5-c-card__title"><div class="pf-v5-c-title pf-m-2xl">${value}</div></div>
                            <div class="pf-v5-c-card__footer">
                                ${title}
                            </div>    
                    </div></div>
datasets:
    ## cards Datasets
    - uuid: uptime
      query:
          query: process_uptime_seconds{${global_filter}}
    - uuid: start_time
      query:
          query: process_start_time_seconds{${global_filter}}
    - uuid: heap_used
      query:
          query: sum(jvm_memory_used_bytes{${global_filter},area="heap"})*100/sum(jvm_memory_max_bytes{${global_filter},area="heap"})
    - uuid: system_cpu_usage
      query:
          query: system_cpu_usage{${global_filter}}
    ## TIMESERIES datasets
    # Memory
    - uuid: heap_used_bytes
      query:
          query: jvm_memory_used_bytes{${global_filter}, area="heap"}${time_window}
    - uuid: nonheap_used_bytes
      query:
          query: jvm_memory_used_bytes{${global_filter}, area="nonheap"}${time_window}
    - uuid: used_bytes_total
      query:
          query: sum by (instance) (jvm_memory_used_bytes{${global_filter}})${time_window}
    # Threads
    - uuid: threads_states
      query:
          query: jvm_threads_states_threads{${global_filter}}${time_window}
    - uuid: live_threads
      query:
          query: jvm_threads_live_threads{${global_filter}}${time_window}
    - uuid: daemon_threads
      query:
          query: jvm_threads_daemon_threads{${global_filter}}${time_window}
      # GC
    - uuid: gc_pause_sum
      query:
          query: jvm_gc_pause_seconds_sum{${global_filter}}${time_window}
    # System
    - uuid: open_files
      query:
          query: process_files_open_files{${global_filter}}${time_window}
    - uuid: system_cpu
      query:
          query: system_cpu_usage{${global_filter}}${time_window}

pages:
    - name: index
      rows:
          - columns:
                - components:
                      - title: JVM Monitoring
                        properties:
                            size: 4xl
                            margin-bottom: 30px

          - columns:
                - span: 3
                  components:
                      - displayer:
                            type: METRIC
                            general:
                                title: Uptime
                            columns:
                                - id: value
                                  expression: >-
                                      var round = Math.round;                                    
                                      var seconds = value;
                                      var minutes = 0;
                                      var hours = 0;
                                      var days = 0;
                                      output = `${seconds}s`;
                                      if (seconds >= 60) {
                                          minutes = round(seconds / 60);
                                          seconds = round(seconds % 60);
                                          if (minutes >= 60) {
                                              hours = round(minutes / 60);
                                              minutes = round(minutes % 60);
                                              if (hours >= 24) {
                                                  days = round(hours / 24);
                                                  hours = round(hours % 24);
                                              }
                                          }
                                      }
                                      `${days}d ${hours}h ${minutes}m ${seconds}s`

                                  pattern: "# min"
                            lookup:
                                uuid: uptime
                                group:
                                    - functions:
                                          - source: value
                - span: 3
                  components:
                      - displayer:
                            type: METRIC
                            general:
                                title: Start Time
                            columns:
                                - id: value
                                  expression: >-
                                      const d = new Date(value * 1000);
                                      const year = d.getFullYear();
                                      const day = d.getDay();
                                      const month = d.getMonth();
                                      const hour = d.getHours();
                                      const minute = `${d.getMinutes()}`.padStart(2, 0);
                                      const second = `${d.getSeconds()}`.padStart(2, 0);
                                      `${hour}:${minute}:${second} ${day}/${month}/${year}`
                            lookup:
                                uuid: start_time
                                group:
                                    - functions:
                                          - source: value
                - span: 3
                  components:
                      - displayer:
                            type: METRIC
                            general:
                                title: Heap Used
                            columns:
                                - id: value
                                  expression: value / 60
                                  pattern: "#.00 %"
                            lookup:
                                uuid: heap_used
                                group:
                                    - functions:
                                          - source: value
                - span: 3
                  components:
                      - displayer:
                            type: METRIC
                            general:
                                title: System CPU Usage
                            columns:
                                - id: value
                                  pattern: "# %"
                            lookup:
                                uuid: system_cpu_usage
                                group:
                                    - functions:
                                          - source: value
          - columns:
                - components:
                      - panel: JVM
                        properties:
                            margin-top: 30px
                      - panel: SYSTEM
                        properties:
                            margin-top: 20px
    - name: JVM
      rows:
          - properties:
                margin-top: 30px
            columns:
                - span: 3
                  components:
                      - displayer:
                            type: TIMESERIES
                            general:
                                title: Heap Memory Used Bytes
                            chart:
                                margin:
                                    left: 10
                            lookup:
                                uuid: heap_used_bytes
                                group:
                                    - functions:
                                          - source: id
                                          - source: timestamp
                                          - source: value
                - span: 3
                  components:
                      - displayer:
                            type: TIMESERIES
                            general:
                                title: NonHeap Memory Used Bytes
                            chart:
                                margin:
                                    left: 10
                            columns:
                                - id: value
                                  pattern: "#"
                            lookup:
                                uuid: nonheap_used_bytes
                                group:
                                    - functions:
                                          - source: id
                                          - source: timestamp
                                          - source: value
                - span: 3
                  components:
                      - displayer:
                            type: TIMESERIES
                            general:
                                title: GC Pause
                            chart:
                                margin:
                                    left: 10
                            lookup:
                                uuid: gc_pause_sum
                                group:
                                    - functions:
                                          - source: cause
                                          - source: timestamp
                                          - source: value
                - span: 3
                  components:
                      - displayer:
                            type: TIMESERIES
                            general:
                                title: Threads States
                            chart:
                                margin:
                                    left: 10
                            lookup:
                                uuid: threads_states
                                group:
                                    - functions:
                                          - source: state
                                          - source: timestamp
                                          - source: value
    - name: SYSTEM
      rows:
          - properties:
                margin-top: 30px
            columns:
                - span: 3
                  components:
                      - displayer:
                            type: TIMESERIES
                            general:
                                title: Heap Total Used Bytes
                            chart:
                                margin:
                                    left: 10
                            lookup:
                                uuid: used_bytes_total
                                group:
                                    - functions:
                                          - source: instance
                                          - source: timestamp
                                          - source: value
                - span: 3
                  components:
                      - displayer:
                            type: TIMESERIES
                            general:
                                title: System CPU
                            extraConfiguration: >-
                                {                                    
                                    "yAxis": {
                                        "max": 100
                                    },
                                    "xAxis": {
                                        "splitNumber": 3
                                    },
                                    "title": {
                                        "textStyle" : { 
                                            "fontSize" : 15
                                        }
                                    }
                                    
                                }

                            columns:
                                - id: value
                                  expression: (new Number(value) *  100).toFixed(3)
                            lookup:
                                uuid: system_cpu
                                group:
                                    - functions:
                                          - source: instance
                                          - source: timestamp
                                          - source: value
                - span: 3
                  components:
                      - displayer:
                            type: TIMESERIES
                            general:
                                title: Live Threads
                            lookup:
                                uuid: live_threads
                                group:
                                    - functions:
                                          - source: instance
                                          - source: timestamp
                                          - source: value
                - span: 3
                  components:
                      - displayer:
                            type: TIMESERIES
                            general:
                                title: Open Files
                            lookup:
                                uuid: open_files
                                group:
                                    - functions:
                                          - source: instance
                                          - source: timestamp
                                          - source: value
