properties:
    ### User properties (you can modify this)
    prometheus_url: http://localhost:9090
    job: keycloak
    refresh_seconds: 10
    period: 1h
    window: 5s

    # style
    subTitleStyle: "padding: 5px; background-color: #F1F1F1; font-size: medium; font-weight: bolder; margin: 5px"
    titleStyle: "font-size: x-large; margin: 5px; font-weight: bold"

    ### Internal Properties
    time_window: "[${period}:${window}]"
    global_filter: 'job="${job}"'
    query_url: ${prometheus_url}/api/v1/query?query=
global:
    mode: dark_
    settings:
        refresh:
            interval: ${refresh_seconds}
        extraConfiguration: >-
            {
                "xAxis": {
                    "splitNumber": 5
                },
                "title": {
                    "textStyle" : { 
                        "fontSize" : 15
                    }
                }
            }
        chart:
            resizable: true
            height: 180
            zoom: true
            margin:
                bottom: 20
                top: 35
            legend:
                show: false
        html:
            html: >-
                <div id="${this}" class="card-pf card-pf-aggregate-status" style="background-color: ${bgColor}; width: 90%; height: 58px;margin: 10px; border-radius: 10px;">
                    <p style="font-weight: 600; font-size: small" id="${this}Title"><em id="${this}Icon" class=""></em> ${title}</p>
                    <h2 style="margin: 5px; font-weight: 600; font-size: large" id="${this}Value">${value} <span id="${this}Suffix" class=""></span></h2>
                </div>
datasets:
    ## cards Datasets
    - uuid: uptime
      type: prometheus
      cacheEnabled: true
      refreshTime: "1second"
      url: ${query_url}process_uptime_seconds{${global_filter}}
    - uuid: start_time
      type: prometheus
      cacheEnabled: true
      refreshTime: "1second"
      url: ${query_url}process_start_time_seconds{${global_filter}}
    - uuid: heap_used
      type: prometheus
      cacheEnabled: true
      refreshTime: "1second"
      url: ${query_url}sum(jvm_memory_used_bytes{${global_filter},area="heap"})*100/sum(jvm_memory_max_bytes{${global_filter},area="heap"})
    - uuid: system_cpu_usage
      type: prometheus
      cacheEnabled: true
      refreshTime: "1second"
      url: ${query_url}system_cpu_usage{${global_filter}}

    ## Timeseries datasets

    # Memory
    - uuid: heap_used_bytes
      type: prometheus
      url: ${query_url}jvm_memory_used_bytes{${global_filter}, area="heap"}${time_window}
      cacheEnabled: true
      refreshTime: "1second"
    - uuid: nonheap_used_bytes
      type: prometheus
      cacheEnabled: true
      refreshTime: "1second"
      url: ${query_url}jvm_memory_used_bytes{${global_filter}, area="nonheap"}${time_window}
    - uuid: used_bytes_total
      type: prometheus
      cacheEnabled: true
      refreshTime: "1second"
      url: ${query_url}sum by (instance) (jvm_memory_used_bytes{${global_filter}})${time_window}

    # Threads
    - uuid: threads_states
      type: prometheus
      cacheEnabled: true
      refreshTime: "1second"
      url: ${query_url}jvm_threads_states_threads{${global_filter}}${time_window}
    - uuid: live_threads
      type: prometheus
      cacheEnabled: true
      refreshTime: "1second"
      url: ${query_url}jvm_threads_live_threads{${global_filter}}${time_window}
    - uuid: daemon_threads
      type: prometheus
      cacheEnabled: true
      refreshTime: "1second"
      url: ${query_url}jvm_threads_daemon_threads{${global_filter}}${time_window}

      # GC
    - uuid: gc_pause_sum
      type: prometheus
      cacheEnabled: true
      refreshTime: "1second"
      url: ${query_url}jvm_gc_pause_seconds_sum{${global_filter}}${time_window}

    # System
    - uuid: open_files
      type: prometheus
      cacheEnabled: true
      refreshTime: "1second"
      url: ${query_url}process_files_open_files{${global_filter}}${time_window}
    - uuid: system_cpu
      type: prometheus
      cacheEnabled: true
      refreshTime: "1second"
      url: ${query_url}system_cpu_usage{${global_filter}}${time_window}

pages:
    - name: index
      rows:
          - _columns:
                - components:
                      - settings:
                            lookup:
                                uuid: live_threads
          - columns:
                - components:
                      - html: >-
                            <p style="${titleStyle}">
                                JVM Monitoring
                                <hr />
                            </p>
          - columns:
                - span: 3
                  components:
                      - settings:
                            type: METRIC
                            general:
                                title: Uptime
                            columns:
                                - id: value
                                  expression: >-
                                      var round = Math.round;                                    
                                      var seconds = value;
                                      var minutes = 0;
                                      var hours = 0;
                                      var days = 0;
                                      output = `${seconds}s`;
                                      if (seconds >= 60) {
                                          minutes = round(seconds / 60);
                                          seconds = round(seconds % 60);
                                          if (minutes >= 60) {
                                              hours = round(minutes / 60);
                                              minutes = round(minutes % 60);
                                              if (hours >= 24) {
                                                  days = round(hours / 24);
                                                  hours = round(hours % 24);
                                              }
                                          }
                                      }
                                      `${days}d ${hours}h ${minutes}m ${seconds}s`

                                  pattern: "# min"
                            lookup:
                                uuid: uptime
                                group:
                                    - functions:
                                          - source: value
                - span: 3
                  components:
                      - settings:
                            type: METRIC
                            general:
                                title: Start Time
                            columns:
                                - id: value
                                  expression: >-
                                      const d = new Date(value * 1000);
                                      const year = d.getFullYear();
                                      const day = d.getDay();
                                      const month = d.getMonth();
                                      const hour = d.getHours();
                                      const minute = `${d.getMinutes()}`.padStart(2, 0);
                                      const second = `${d.getSeconds()}`.padStart(2, 0);
                                      `${hour}:${minute}:${second} ${day}/${month}/${year}`
                            lookup:
                                uuid: start_time
                                group:
                                    - functions:
                                          - source: value
                - span: 3
                  components:
                      - settings:
                            type: METRIC
                            general:
                                title: Heap Used
                            columns:
                                - id: value
                                  expression: value / 60
                                  pattern: "#.00 %"
                            lookup:
                                uuid: heap_used
                                group:
                                    - functions:
                                          - source: value
                - span: 3
                  components:
                      - settings:
                            type: METRIC
                            general:
                                title: System CPU Usage
                            columns:
                                - id: value
                                  pattern: "# %"
                            lookup:
                                uuid: system_cpu_usage
                                group:
                                    - functions:
                                          - source: value
          - columns:
                - components:
                      - panel: JVM
                      - panel: SYSTEM
    - name: JVM
      rows:
          - properties:
                margin-top: 30px
            columns:
                - span: 3
                  components:
                      - settings:
                            type: timeseries
                            general:
                                title: Heap Memory Used Bytes
                            chart:
                                margin:
                                    left: 80
                            lookup:
                                uuid: heap_used_bytes
                                group:
                                    - functions:
                                          - source: id
                                          - source: timestamp
                                          - source: value
                - span: 3
                  components:
                      - settings:
                            type: timeseries
                            general:
                                title: NonHeap Memory Used Bytes
                            chart:
                                margin:
                                    left: 80
                            columns:
                                - id: value
                                  pattern: "#"
                            lookup:
                                uuid: nonheap_used_bytes
                                group:
                                    - functions:
                                          - source: id
                                          - source: timestamp
                                          - source: value
                - span: 3
                  components:
                      - settings:
                            type: timeseries
                            general:
                                title: GC Pause
                            chart:
                                margin:
                                    left: 35
                            lookup:
                                uuid: gc_pause_sum
                                group:
                                    - functions:
                                          - source: cause
                                          - source: timestamp
                                          - source: value
                - span: 3
                  components:
                      - settings:
                            type: timeseries
                            general:
                                title: Threads States
                            chart:
                                margin:
                                    left: 35
                            lookup:
                                uuid: threads_states
                                group:
                                    - functions:
                                          - source: state
                                          - source: timestamp
                                          - source: value
    - name: SYSTEM
      rows:
          - properties:
                margin-top: 30px
            columns:
                - span: 3
                  components:
                      - settings:
                            type: timeseries
                            general:
                                title: Heap Total Used Bytes
                            chart:
                                margin:
                                    left: 85

                            lookup:
                                uuid: used_bytes_total
                                group:
                                    - functions:
                                          - source: instance
                                          - source: timestamp
                                          - source: value
                - span: 3
                  components:
                      - settings:
                            type: timeseries
                            general:
                                title: System CPU
                            extraConfiguration: >-
                                {
                                    
                                    "yAxis": {
                                        "max": 1
                                    },
                                    "xAxis": {
                                        "splitNumber": 5
                                    },
                                    "title": {
                                        "textStyle" : { 
                                            "fontSize" : 15
                                        }
                                    }
                                    
                                }
                            columns:
                                - id: value
                                  expression: "value * 100"
                            lookup:
                                uuid: system_cpu
                                group:
                                    - functions:
                                          - source: instance
                                          - source: timestamp
                                          - source: value
                - span: 3
                  components:
                      - settings:
                            type: timeseries
                            general:
                                title: Live Threads
                            lookup:
                                uuid: live_threads
                                group:
                                    - functions:
                                          - source: instance
                                          - source: timestamp
                                          - source: value
                - span: 3
                  components:
                      - settings:
                            type: timeseries
                            general:
                                title: Open Files
                            columns:
                                - id: value
                                  expression: "#"
                            lookup:
                                uuid: open_files
                                group:
                                    - functions:
                                          - source: instance
                                          - source: timestamp
                                          - source: value
