datasets:
  - uuid: jvm_used_memory
    expression: "$reduce($map($.data.result, function($v) {$map($v.values, function($r, $i) {[$v.metric.instance, $v.metric.id, $r[0] * 1000, $r[1]]})}), $append)"
    url: http://localhost:9090/api/v1/query?query=jvm_memory_used_bytes[30m:5s]
pages:
  - name: JVM Memory Usage
    rows:
      - columns:
          - components:
              - HTML: <br /> <strong>JVM Memory Usage</strong><hr />
                properties:
                  font-size: large
                  margin-left: 10px
          - components:
              - settings:
                  component: timeseries
                  timeseries:
                    legend:
                      bottom: "5%"
                  external:
                    width: 100%
                    height: 400px
                  refresh:
                    interval: "5"
                  lookup:
                    uuid: jvm_used_memory
                    group:
                      - functions:
                          - source: Column 1
                          - source: Column 2
                          - source: Column 3
