global:
  settings:
    refresh:
      interval: 5
    html:
      html: >-
        <div id="${this}" class="card-pf card-pf-aggregate-status" style="background-color: ${bgColor}; width: 90%; height: 80px;margin: 10px; border-radius: 10px">
          <h2 style="font-weight: 600; font-size: large" id="${this}Value">${value} <span id="${this}Suffix" class=""></span></h2>
          <p style="font-weight: 400" id="${this}Title"><em id="${this}Icon" class=""></em> ${title}</p>
        </div>
datasets:
  - uuid: threads
    expression: "$reduce($map($.data.result, function($v) {$map($v.values, function($r, $i) {[$v.metric.instance, $v.metric.state, $r[0] * 1000, $r[1]]})}), $append)"
    url: http://localhost:9090/api/v1/query?query=jvm_threads_states_threads[10m:1s]
  - uuid: live_threads
    expression: "$.data.result.[metric.instance, value[1]]"
    url: http://localhost:9090/api/v1/query?query=jvm_threads_live_threads
  - uuid: daemon_threads
    expression: "$.data.result.[metric.instance, value[1]]"
    url: http://localhost:9090/api/v1/query?query=jvm_threads_daemon_threads
  - uuid: peak_threads
    expression: "$.data.result.[metric.instance, value[1]]"
    url: http://localhost:9090/api/v1/query?query=jvm_threads_peak_threads
pages:
  - name: Threads
    rows:
      - columns:
          - span: 4
            components:
              - html: Threads <hr />
                properties:                  
                  font-size: x-large
      - columns:
          - span: 4
            components:
              - settings:
                  type: METRIC
                  general:
                    title: Live
                  columns:
                    - id: Column 1
                      pattern: "#"
                  dataSetLookup:
                    uuid: live_threads
                    groupOps:
                      - groupFunctions:
                          - source: Column 1
          - span: 4
            components:
              - settings:
                  type: METRIC
                  general:
                    title: Daemon
                  columns:
                    - id: Column 1
                      pattern: "#"
                  refresh:
                    interval: "5"
                  lookup:
                    uuid: daemon_threads
                    groupOps:
                      - groupFunctions:
                          - source: Column 1
          - span: 4
            components:
              - settings:
                  type: METRIC
                  general:
                    title: Peak
                  columns:
                    - id: Column 1
                      pattern: "#"
                  lookup:
                    uuid: peak_threads
                    group:
                      - functions:
                          - source: Column 1
      - columns:
          - components:
              - html: <br /> Thread States<hr />
                properties:
                  font-size: large
          - components:
              - settings:
                  component: timeseries
                  timeseries:
                    legend:
                      bottom: "5%"
                  external:
                    width: 100%
                    height: 400px
                  lookup:
                    uuid: threads
                    group:
                      - functions:
                          - source: Column 1
                          - source: Column 2
                          - source: Column 3
