properties:
    # use -1 for no update
    update: 10
    height: 300px
    prometheus_url: https://prometheus-portal-kogito-tooling-rhods.rhba-cluster-0ad6762cc85bcef5745bb684498c2436-0000.us-south.containers.appdomain.cloud
    time_window: "[1h:10s]"
    requests_by_instance_total_query: sum by(instance) (traefik_backend_request_duration_seconds_count)
    requests_by_code_query: sum by(code) (traefik_backend_request_duration_seconds_count)
    parser: >-
        >-
                $.data.(
                    {
                        "columns": result[0].(
                            [
                                {"id" : "timestamp", "type": "number"}, 
                                {"id" : "value", "type": "number"},
                                $keys(metric).({"id" : $, "type": "label"})
                            ];
                        ),
                        "values": (
                            resultType = "scalar" ? [result[0] * 1000, result[1]] :
                            resultType = "matrix" ? result.( $metric := metric.*; values.[ $[0] * 1000, $[1], $metric ] ) :
                            resultType = "vector" ?  result.[ value[0] * 1000, value[1],  metric.* ]
                        )
                    }
                )
datasets:
    - uuid: memory
      url: ${prometheus_url}/api/v1/query?query=${memory_query}
      expression: ${parser}
    - uuid: requests_total
      url: ${prometheus_url}/api/v1/query?query=${requests_by_instance_total_query}${time_window}
      expression: ${parser}
    - uuid: requests_by_code_query
      url: ${prometheus_url}/api/v1/query?query=${requests_by_code_query}${time_window}
      expression: ${parser}
pages:
    - components:
          - html: <strong>Traefik Metrics</strong> <hr />
            properties:
                font-size: x-large
          - settings:
                component: timeseries
                timeseries:
                    tooltip:
                        confine: "true"
                    title:
                        show: true
                        text: Requests by Endpoint
                    legend:
                        show: "true"
                        bottom: "center"
                        top: bottom
                external:
                    width: 100%
                    height: ${height}
                refresh:
                    interval: "${update}"
                lookup:
                    uuid: requests_total
                    group:
                        - functions:
                              - source: instance
                              - source: timestamp
                              - source: value
          - properties:
                margin-top: 50px
            settings:
                component: timeseries
                timeseries:
                    tooltip:
                        confine: "true"
                    title:
                        show: true
                        text: Requests by Response Code
                    legend:
                        show: "true"
                        bottom: "center"
                        top: bottom
                external:
                    width: 100%
                    height: ${height}
                refresh:
                    interval: "${update}"
                lookup:
                    uuid: requests_by_code_query
                    group:
                        - functions:
                              - source: code
                              - source: timestamp
                              - source: value
